POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTM1ODE5NDUsInVzZXJJZCI6MX0.xg4srHbjnawJNUrQloAOi-eS_muO7crId57LXq445Gg

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}