POST http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzEzNTgyMDc5LCJ1c2VySWQiOjJ9.H7v2AUFUcIyUXwn875HZUux-dj8VJne92NNIWbqAPC8